### ISSUE TITLE
What is hi

### ISSUE THREAD

**Issue by mutouyuguo** [codeyuguo/hi#1]
- begin with a question, or some error log
- hi will give some answers
- you may satisfied or provide more clue
- maybe after 3 rounds
- you get the answer or turn to google
- hi should also provide online debug env, you can verify the problem

**Comment by QG-Fly** [comment]
I hope Hi is like an artificial intelligence robot, helping users solve problems through dialogue

**Comment by freeJoyful** [comment]
How will the Hi look like ?In my opinion, she is as simple as google , but not just a replica of google's UI .

**Comment by mutouyuguo** [comment]
Just do it, guys!
