### ISSUE TITLE
a simple chat box

### ISSUE THREAD

**Issue by mutouyuguo** [codeyuguo/hi#17]
design a simple chat box

**Comment by mutouyuguo** [comment]
@codeyuguo/salut everyone, some idea about the chat box?

**Comment by chaifanfan** [comment]
Before I work on it, I need to know more information about it, like what kind of style we want to show or what the most special point we want to build. All in detail. Maybe we should have a discussion later.
@codeyuguo/salut

**Comment by mutouyuguo** [comment]
https://www.autodraw.com/
"do you mean" is very interesting @codeyuguo/salut
